name: TesteForca CI/CD

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Usando Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x

      - name: Instalar dependências
        run: npm install

      - name: Build
        run: npm run build

      - name: Executar testes
        run: npm test
