name: TesteForca CI/CD

on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Usando Node.js
      - uses: actions/setup-node@v4
        
        with:
          node-version: 22.x
      - name: run instalacao e teste
      - run: |
          npm install
          npm run build
          npm test
